
host: http://10.10.30.3:9090

start_time: 1709226028
end_time: 1709301817

aggregate:
  dir: nasa@genesisrm-sg-l2
  out: nasa@genesisrm-sg-l2-aggregated
  exp: swiftkube   # autothrottle hpa ahpa swiftkube default

