train_ticket:
  k8s:
    namespace: train-ticket 

  frontend_endpoints:
    - 
      service_name: travel-plan-service
      endpoint_name: POST@/api/v1/travelplanservice/travelPlan/cheapest
    - 
      service_name: food-service 
      endpoint_name: GET@/api/v1/foodservice/foods/{*}/{*}/{*}/{*}

  configs:
    - 
      service_name: travel-plan-service 
      k8s_dep_name: travel-plan-dep 
      resources:
        - name: travel-plan-service
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "980m"
      worker:
        target_utilization: 70
        max: 20 
      replicas:
        max: 15 
        min: 1 
    - 
      service_name: food-service 
      k8s_dep_name: food-dep 
      resources:
        - name: food-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "710m"
      worker:
        target_utilization: 70
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: basic-service 
      k8s_dep_name: basic-dep 
      resources:
        - name: basic-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "2200m"
      worker:
        target_utilization: 30
        max: 20
      replicas:
        max: 20
        min: 1 
    - 
      service_name: config-service 
      k8s_dep_name: config-dep 
      resources:
        - name: config-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "710m"
      worker:
        target_utilization: 5
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: food-map-service 
      k8s_dep_name: food-map-dep 
      resources:
        - name: food-map-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "510m"
      worker:
        target_utilization: 5
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: order-service 
      k8s_dep_name: order-dep 
      resources:
        - name: order-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "850m"
      worker:
        target_utilization: 5
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: price-service 
      k8s_dep_name: price-dep 
      resources:
        - name: price-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "200m"
      worker:
        target_utilization: 5
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: route-plan-service 
      k8s_dep_name: route-plan-dep 
      resources:
        - name: route-plan-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "650m"
      worker:
        target_utilization: 70
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: route-service 
      k8s_dep_name: route-dep 
      resources:
        - name: route-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "1900m"
      worker:
        target_utilization: 13
        max: 20
      replicas:
        max: 20
        min: 1 
    - 
      service_name: seat-service 
      k8s_dep_name: seat-dep 
      resources:
        - name: seat-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "1900m"
      worker:
        target_utilization: 35
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: station-service 
      k8s_dep_name: station-dep 
      resources:
        - name: station-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "2100m"
      worker:
        target_utilization: 19
        max: 20
      replicas:
        max: 20
        min: 1 
    -
      service_name: ticketinfo-service 
      k8s_dep_name: ticketinfo-dep 
      resources:
        - name: ticketinfo-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "2100m"
      worker:
        target_utilization: 40
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: train-service 
      k8s_dep_name: train-dep 
      resources:
        - name: train-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "950m"
      worker:
        target_utilization: 7
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: travel-b-service 
      k8s_dep_name: travel-b-dep 
      resources:
        - name: travel-b-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "2100m"
      worker:
        target_utilization: 18
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: travel-service 
      k8s_dep_name: travel-dep 
      resources:
        - name: travel-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "2000m"
      worker:
        target_utilization: 50
        max: 20
      replicas:
        max: 15 
        min: 1 
    -
      service_name: travel2-service 
      k8s_dep_name: travel2-dep 
      resources:
        - name: travel2-service 
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "2048Mi"
              cpu: "830m"
      worker:
        target_utilization: 12
        max: 20
      replicas:
        max: 15 
        min: 1 

enabled_service_config: train_ticket 

base:
  prometheus:
    host: http://10.10.30.3:9090

  locust:
    workload: nasa 
    workers: 40
    url: http://10.10.30.4:9000

  postgresql:
    host: 10.10.30.3 
    user: postgres 
    database: trainticket 
    password: Admin@123_.
    port: 5432 

  neo4j:
    url: bolt://10.10.30.3:7687
    project: trainticket 

  kubernetes:
    master: 'https://10.10.30.3:6443'


ts_predictor:
  enbpi: 
    history_len: 180
    sample_x_len: 30
    sample_y_len: 5
    alpha: 0.01
    db:
      table_name: span_stats 
      
  deepar:
    model: deepar/train_ticket


scaler:
  enabled_scaler: swiftkube_scaler 

  none: {}  

  cb_scaler:
    groups:
      - services:
          - travel-plan-service 
        threshold: [0.5, 0.75, 1]
      - services:
          - basic-service 
        threshold: [0.25, 0.5, 0.75]
      
  nw_scaler:
    author: zdh

  ahpa_scaler: 
    T: 14400
    H: 60
    lambda_1: 288
    lambda_2: 144
    delta_d: 10
    delta_i: 5

    forecast_length: 14400
    # quantile: 0.9
    trim_left: 2000
    trim_right: 1000

    guessd_delay: 300
    throughput: 0.3

    alpha: 0.9
    lam1: 1.0
    lam2: 1.0
    gamma: 1.0

    namespace: train-ticket
    # st_fetch_minutes: 6
    # st_history_len: 30
    st_fetch_minutes: 2
    st_history_len: 20
    wait: 180

    db:
      table_name: span_stats 

    rate:
      cpu_scale_rate: 0.75
      scale_in_rate: 1.4

    freq:
      scale_in_freq: 15
      scale_out_freq: 60

  swiftkube_scaler: 
    min_cpu_limit: "10m"
    #strategy: 'rt'  # rt rt-l1 rt-l1-l2 rt-l2
    strategy: "SGS-L2"

    kafka:
      topic: flink-span-stats
      bootstrap_servers: "10.10.30.3:9092,10.10.30.93:9092,10.10.30.95:9092,10.10.30.96:9092,10.10.30.98:9092,10.10.30.99:9092"
  
  k8s_vpa_scaler: {}

  mem_scaler:
    locust_enabled: false 

