defaults:
  - service_config: train-ticket-schutzstaffel 
  - autoscaler: none
  - ts_predictor: default 
  - locust: test_hpa 
  - _self_

base:
  prometheus:
    host: http://10.10.30.3:9090

  postgresql:
    host: 10.10.30.3 
    user: postgres 
    database: trainticket 
    password: Admin@123_.
    port: 5432 

  neo4j:
    url: bolt://10.10.30.3:7687
    project: trainticket 

  kubernetes:
    master: 'https://10.10.30.3:6443'

  appmanager:
    host: 'localhost:10000'

cmd:
  autoweight:
    host: '127.0.0.1:8000'

    

