# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/elastic-deployment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/elastic-deployment.proto',
  package='elastic_deployment',
  syntax='proto3',
  serialized_options=_b('Z\033scut.edu.cn/microkube/proto'),
  serialized_pb=_b('\n\x1eproto/elastic-deployment.proto\x12\x12\x65lastic_deployment\"-\n\x08Response\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\r\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"-\n\nDeployment\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"g\n\x1c\x44\x65ploymentReplicasOpsRequest\x12.\n\x06target\x18\x01 \x01(\x0b\x32\x1e.elastic_deployment.Deployment\x12\x17\n\x0ftarget_replicas\x18\x02 \x01(\x05\"C\n\x15\x44\x65ploymentOpsResponse\x12*\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x1c.elastic_deployment.Response\"]\n\x1d\x44\x65ploymentGetReplicasResponse\x12*\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x1c.elastic_deployment.Response\x12\x10\n\x08replicas\x18\x02 \x01(\x05\"!\n\x10NameListResponse\x12\r\n\x05names\x18\x01 \x03(\t2\x8c\x06\n\x14\x44\x65ploymentOperations\x12o\n\x0eSetPodReplicas\x12\x30.elastic_deployment.DeploymentReplicasOpsRequest\x1a).elastic_deployment.DeploymentOpsResponse\"\x00\x12v\n\x15SetRunningPodReplicas\x12\x30.elastic_deployment.DeploymentReplicasOpsRequest\x1a).elastic_deployment.DeploymentOpsResponse\"\x00\x12\x65\n\x0eGetPodReplicas\x12\x1e.elastic_deployment.Deployment\x1a\x31.elastic_deployment.DeploymentGetReplicasResponse\"\x00\x12q\n\x1aGetInitializingPodReplicas\x12\x1e.elastic_deployment.Deployment\x1a\x31.elastic_deployment.DeploymentGetReplicasResponse\"\x00\x12m\n\x16GetRunnablePodReplicas\x12\x1e.elastic_deployment.Deployment\x1a\x31.elastic_deployment.DeploymentGetReplicasResponse\"\x00\x12l\n\x15GetRunningPodReplicas\x12\x1e.elastic_deployment.Deployment\x1a\x31.elastic_deployment.DeploymentGetReplicasResponse\"\x00\x12T\n\x08GetNames\x12 .elastic_deployment.EmptyRequest\x1a$.elastic_deployment.NameListResponse\"\x00\x42\x1dZ\x1bscut.edu.cn/microkube/protob\x06proto3')
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='elastic_deployment.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='elastic_deployment.Response.err_code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='elastic_deployment.Response.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=99,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='elastic_deployment.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=115,
)


_DEPLOYMENT = _descriptor.Descriptor(
  name='Deployment',
  full_name='elastic_deployment.Deployment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='elastic_deployment.Deployment.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='elastic_deployment.Deployment.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=162,
)


_DEPLOYMENTREPLICASOPSREQUEST = _descriptor.Descriptor(
  name='DeploymentReplicasOpsRequest',
  full_name='elastic_deployment.DeploymentReplicasOpsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='elastic_deployment.DeploymentReplicasOpsRequest.target', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_replicas', full_name='elastic_deployment.DeploymentReplicasOpsRequest.target_replicas', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=267,
)


_DEPLOYMENTOPSRESPONSE = _descriptor.Descriptor(
  name='DeploymentOpsResponse',
  full_name='elastic_deployment.DeploymentOpsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='elastic_deployment.DeploymentOpsResponse.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=336,
)


_DEPLOYMENTGETREPLICASRESPONSE = _descriptor.Descriptor(
  name='DeploymentGetReplicasResponse',
  full_name='elastic_deployment.DeploymentGetReplicasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='elastic_deployment.DeploymentGetReplicasResponse.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replicas', full_name='elastic_deployment.DeploymentGetReplicasResponse.replicas', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=431,
)


_NAMELISTRESPONSE = _descriptor.Descriptor(
  name='NameListResponse',
  full_name='elastic_deployment.NameListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='elastic_deployment.NameListResponse.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=466,
)

_DEPLOYMENTREPLICASOPSREQUEST.fields_by_name['target'].message_type = _DEPLOYMENT
_DEPLOYMENTOPSRESPONSE.fields_by_name['base'].message_type = _RESPONSE
_DEPLOYMENTGETREPLICASRESPONSE.fields_by_name['base'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['Deployment'] = _DEPLOYMENT
DESCRIPTOR.message_types_by_name['DeploymentReplicasOpsRequest'] = _DEPLOYMENTREPLICASOPSREQUEST
DESCRIPTOR.message_types_by_name['DeploymentOpsResponse'] = _DEPLOYMENTOPSRESPONSE
DESCRIPTOR.message_types_by_name['DeploymentGetReplicasResponse'] = _DEPLOYMENTGETREPLICASRESPONSE
DESCRIPTOR.message_types_by_name['NameListResponse'] = _NAMELISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.Response)
  ))
_sym_db.RegisterMessage(Response)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

Deployment = _reflection.GeneratedProtocolMessageType('Deployment', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENT,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.Deployment)
  ))
_sym_db.RegisterMessage(Deployment)

DeploymentReplicasOpsRequest = _reflection.GeneratedProtocolMessageType('DeploymentReplicasOpsRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTREPLICASOPSREQUEST,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.DeploymentReplicasOpsRequest)
  ))
_sym_db.RegisterMessage(DeploymentReplicasOpsRequest)

DeploymentOpsResponse = _reflection.GeneratedProtocolMessageType('DeploymentOpsResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTOPSRESPONSE,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.DeploymentOpsResponse)
  ))
_sym_db.RegisterMessage(DeploymentOpsResponse)

DeploymentGetReplicasResponse = _reflection.GeneratedProtocolMessageType('DeploymentGetReplicasResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTGETREPLICASRESPONSE,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.DeploymentGetReplicasResponse)
  ))
_sym_db.RegisterMessage(DeploymentGetReplicasResponse)

NameListResponse = _reflection.GeneratedProtocolMessageType('NameListResponse', (_message.Message,), dict(
  DESCRIPTOR = _NAMELISTRESPONSE,
  __module__ = 'proto.elastic_deployment_pb2'
  # @@protoc_insertion_point(class_scope:elastic_deployment.NameListResponse)
  ))
_sym_db.RegisterMessage(NameListResponse)


DESCRIPTOR._options = None

_DEPLOYMENTOPERATIONS = _descriptor.ServiceDescriptor(
  name='DeploymentOperations',
  full_name='elastic_deployment.DeploymentOperations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=469,
  serialized_end=1249,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetPodReplicas',
    full_name='elastic_deployment.DeploymentOperations.SetPodReplicas',
    index=0,
    containing_service=None,
    input_type=_DEPLOYMENTREPLICASOPSREQUEST,
    output_type=_DEPLOYMENTOPSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetRunningPodReplicas',
    full_name='elastic_deployment.DeploymentOperations.SetRunningPodReplicas',
    index=1,
    containing_service=None,
    input_type=_DEPLOYMENTREPLICASOPSREQUEST,
    output_type=_DEPLOYMENTOPSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPodReplicas',
    full_name='elastic_deployment.DeploymentOperations.GetPodReplicas',
    index=2,
    containing_service=None,
    input_type=_DEPLOYMENT,
    output_type=_DEPLOYMENTGETREPLICASRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInitializingPodReplicas',
    full_name='elastic_deployment.DeploymentOperations.GetInitializingPodReplicas',
    index=3,
    containing_service=None,
    input_type=_DEPLOYMENT,
    output_type=_DEPLOYMENTGETREPLICASRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRunnablePodReplicas',
    full_name='elastic_deployment.DeploymentOperations.GetRunnablePodReplicas',
    index=4,
    containing_service=None,
    input_type=_DEPLOYMENT,
    output_type=_DEPLOYMENTGETREPLICASRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRunningPodReplicas',
    full_name='elastic_deployment.DeploymentOperations.GetRunningPodReplicas',
    index=5,
    containing_service=None,
    input_type=_DEPLOYMENT,
    output_type=_DEPLOYMENTGETREPLICASRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNames',
    full_name='elastic_deployment.DeploymentOperations.GetNames',
    index=6,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_NAMELISTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPLOYMENTOPERATIONS)

DESCRIPTOR.services_by_name['DeploymentOperations'] = _DEPLOYMENTOPERATIONS

# @@protoc_insertion_point(module_scope)
