# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import elastic_deployment_pb2 as proto_dot_elastic__deployment__pb2


class DeploymentOperationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetPodReplicas = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/SetPodReplicas',
        request_serializer=proto_dot_elastic__deployment__pb2.DeploymentReplicasOpsRequest.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.DeploymentOpsResponse.FromString,
        )
    self.SetRunningPodReplicas = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/SetRunningPodReplicas',
        request_serializer=proto_dot_elastic__deployment__pb2.DeploymentReplicasOpsRequest.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.DeploymentOpsResponse.FromString,
        )
    self.GetPodReplicas = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/GetPodReplicas',
        request_serializer=proto_dot_elastic__deployment__pb2.Deployment.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.FromString,
        )
    self.GetInitializingPodReplicas = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/GetInitializingPodReplicas',
        request_serializer=proto_dot_elastic__deployment__pb2.Deployment.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.FromString,
        )
    self.GetRunnablePodReplicas = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/GetRunnablePodReplicas',
        request_serializer=proto_dot_elastic__deployment__pb2.Deployment.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.FromString,
        )
    self.GetRunningPodReplicas = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/GetRunningPodReplicas',
        request_serializer=proto_dot_elastic__deployment__pb2.Deployment.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.FromString,
        )
    self.GetNames = channel.unary_unary(
        '/elastic_deployment.DeploymentOperations/GetNames',
        request_serializer=proto_dot_elastic__deployment__pb2.EmptyRequest.SerializeToString,
        response_deserializer=proto_dot_elastic__deployment__pb2.NameListResponse.FromString,
        )


class DeploymentOperationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetPodReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetRunningPodReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPodReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInitializingPodReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRunnablePodReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRunningPodReplicas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNames(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeploymentOperationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetPodReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.SetPodReplicas,
          request_deserializer=proto_dot_elastic__deployment__pb2.DeploymentReplicasOpsRequest.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.DeploymentOpsResponse.SerializeToString,
      ),
      'SetRunningPodReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.SetRunningPodReplicas,
          request_deserializer=proto_dot_elastic__deployment__pb2.DeploymentReplicasOpsRequest.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.DeploymentOpsResponse.SerializeToString,
      ),
      'GetPodReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.GetPodReplicas,
          request_deserializer=proto_dot_elastic__deployment__pb2.Deployment.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.SerializeToString,
      ),
      'GetInitializingPodReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.GetInitializingPodReplicas,
          request_deserializer=proto_dot_elastic__deployment__pb2.Deployment.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.SerializeToString,
      ),
      'GetRunnablePodReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.GetRunnablePodReplicas,
          request_deserializer=proto_dot_elastic__deployment__pb2.Deployment.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.SerializeToString,
      ),
      'GetRunningPodReplicas': grpc.unary_unary_rpc_method_handler(
          servicer.GetRunningPodReplicas,
          request_deserializer=proto_dot_elastic__deployment__pb2.Deployment.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.DeploymentGetReplicasResponse.SerializeToString,
      ),
      'GetNames': grpc.unary_unary_rpc_method_handler(
          servicer.GetNames,
          request_deserializer=proto_dot_elastic__deployment__pb2.EmptyRequest.FromString,
          response_serializer=proto_dot_elastic__deployment__pb2.NameListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'elastic_deployment.DeploymentOperations', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
