# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/microkube-autoscaler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/microkube-autoscaler.proto',
  package='microkube_autoscaler',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n proto/microkube-autoscaler.proto\x12\x14microkube_autoscaler\"\x0e\n\x0c\x45mptyRequest\"\x1d\n\x0c\x42oolResponse\x12\r\n\x05value\x18\x01 \x01(\x08\x32\x61\n\nAutoscaler\x12S\n\x07IsReady\x12\".microkube_autoscaler.EmptyRequest\x1a\".microkube_autoscaler.BoolResponse\"\x00\x62\x06proto3')
)




_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='microkube_autoscaler.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=72,
)


_BOOLRESPONSE = _descriptor.Descriptor(
  name='BoolResponse',
  full_name='microkube_autoscaler.BoolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='microkube_autoscaler.BoolResponse.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['BoolResponse'] = _BOOLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'proto.microkube_autoscaler_pb2'
  # @@protoc_insertion_point(class_scope:microkube_autoscaler.EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

BoolResponse = _reflection.GeneratedProtocolMessageType('BoolResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOLRESPONSE,
  __module__ = 'proto.microkube_autoscaler_pb2'
  # @@protoc_insertion_point(class_scope:microkube_autoscaler.BoolResponse)
  ))
_sym_db.RegisterMessage(BoolResponse)



_AUTOSCALER = _descriptor.ServiceDescriptor(
  name='Autoscaler',
  full_name='microkube_autoscaler.Autoscaler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='IsReady',
    full_name='microkube_autoscaler.Autoscaler.IsReady',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_BOOLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOSCALER)

DESCRIPTOR.services_by_name['Autoscaler'] = _AUTOSCALER

# @@protoc_insertion_point(module_scope)
